// SPDX-License-Identifier: Apache-2.0
//
// Register NIGHT UTXOs for DUST generation. DUST pays transaction fees and
// cannot be bought — it is generated by registered NIGHT, so this must happen
// once before a freshly funded testnet wallet can submit anything.
//
// Ported from midnightntwrk/midnight-local-dev.
import { Buffer } from 'node:buffer';
import * as Rx from 'rxjs';
import { NETWORK, networkConfig } from '../config.js';
import { resolveSeed } from '../seed.js';
import { initializeNetwork } from '../netid.js';
import { buildWallet, startAndSync } from '../wallet.js';
import { note, ok, fail } from '../display.js';
import { withRetries, describe as describeErr, errorCode, LEDGER_ERRORS } from '../retry.js';

/**
 * After registration `dust.balance(now)` becomes non-zero as DUST accrues, but
 * a *spendable* coin is not minted until the chain produces blocks accounting
 * for that accrual. `availableCoins.length >= 1` is the correct readiness
 * signal; `balance > 0` is not.
 */
async function waitForSpendableDust(facade: any, timeoutMs = 900_000) {
  const started = Date.now();
  for (;;) {
    const st: any = await Rx.firstValueFrom(facade.state());
    const coins = st.dust?.availableCoins?.length ?? 0;
    const bal = (() => { try { return st.dust?.balance(new Date()) ?? 0n; } catch { return 0n; } })();
    const secs = Math.floor((Date.now() - started) / 1000);
    process.stdout.write(`\r  waiting for spendable DUST… coins=${coins} balance=${bal} (${secs}s)   `);
    if (coins >= 1) { process.stdout.write('\n'); return true; }
    if (Date.now() - started > timeoutMs) { process.stdout.write('\n'); return false; }
    await new Promise((r) => setTimeout(r, 5000));
  }
}

export async function registerDust() {
  initializeNetwork();
  note(`network: ${NETWORK}   node: ${networkConfig.node}`);

  const bundle = await buildWallet(resolveSeed(), { useCheckpoint: false });
  await startAndSync(bundle, 600_000);

  const st: any = await Rx.firstValueFrom(bundle.facade.state());
  const unregistered = (st.unshielded?.availableCoins ?? [])
    .filter((c: any) => c.meta?.registeredForDustGeneration === false);

  note(`NIGHT UTXOs: ${st.unshielded?.availableCoins?.length ?? 0}, unregistered: ${unregistered.length}`);

  if (unregistered.length === 0) {
    const coins = st.dust?.availableCoins?.length ?? 0;
    if (coins >= 1) { ok(`Already registered — ${coins} spendable DUST coin(s).`); process.exit(0); }
    note('Nothing to register; waiting for DUST to become spendable…');
    ok((await waitForSpendableDust(bundle.facade)) ? 'DUST ready.' : 'DUST not ready yet — rerun later.');
    process.exit(0);
  }

  note(`Registering ${unregistered.length} NIGHT UTXO(s) for DUST generation…`);
  let txId: string;
  try {
    txId = await withRetries('register-dust', async () => {
      const recipe = await bundle.facade.registerNightUtxosForDustGeneration(
        unregistered,
        bundle.keystore.getPublicKey(),
        (payload: any) => bundle.keystore.signData(payload),
      );
      const finalized = await bundle.facade.finalizeRecipe(recipe);
      return bundle.facade.submitTransaction(finalized);
    });
  } catch (e) {
    const code = errorCode(e);
    fail(`registration rejected${code ? ` — Custom(${code}) ${LEDGER_ERRORS[code] ?? 'UNMAPPED'}` : ''}`);
    note(describeErr(e).slice(0, 400));
    process.exit(1);
  }
  ok(`DUST registration submitted: ${txId}`);

  ok((await waitForSpendableDust(bundle.facade)) ? 'DUST is spendable — ready to deploy.' : 'Registered, but DUST not spendable yet — rerun `nominee balance` shortly.');
  process.exit(0);
}
